openapi: 3.0.1
info:
  title: sparta-ecommerce API
  description: sparta-ecommerce API 스펙 문서
  version: 1.0.0
servers:
- url: http://localhost:8081
tags: []
paths: {}
components:
  schemas: {}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      name: Authorization
      in: header
      description: "Use 'your-access-token' as the value of the Authorization header"
security:
  - bearerAuth: []  # Apply the security scheme here