plugins {
    id 'java-library'
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

dependencies {
    // Lombok only - for reducing boilerplate code
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}

// 라이브러리 모듈이므로 bootJar 비활성화
tasks.named('bootJar') {
    enabled = false
}

// jar 활성화
tasks.named('jar') {
    enabled = true
}
