rootProject.name = 'ai-commerce-platform'

// Shared libraries
include("libs:common-core")
include("libs:common-web")
include("libs:common-security")
include("libs:common-kafka")
include("libs:common-observability")
include("libs:common-test")

// Services
include("services:gateway-service")
include("services:auth-service")
include("services:user-service")
include("services:catalog-service")
include("services:order-service")
include("services:point-service")
include("services:payment-service")
include("services:chat-service")