ext {
    set('springCloudVersion', "2025.0.0")
}

dependencies {
    implementation project(':common')

    implementation 'org.springframework.cloud:spring-cloud-starter-gateway-server-webflux'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'

    // Redis (for JWT blacklist and Passport )
    implementation 'org.springframework.boot:spring-boot-starter-data-redis-reactive'

    // Kafka (for audit logging)
    implementation 'org.springframework.kafka:spring-kafka'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

tasks.named('bootJar') {
    enabled = true
}
